<?php

return [
    'palabras_prohibidas' => [
        // Palabras iniciales
        'puto', 'Puto', 'PUTO',
        'ofensiva', 'Ofensiva', 'OFENSIVA',
        'grosera', 'Grosera', 'GROsera',
        'puta', 'Puta', 'PUTA',
        'verga', 'Verga', 'VERGA',
        'zorra', 'Zorra', 'ZORRA',
        'pendejo', 'Pendejo', 'PENDEJO',
        'pendeja', 'Pendeja', 'PENDEJA',
        'pene', 'Pene', 'PENE',
        'sexo', 'Sexo', 'SEXO',
        'nazi', 'Nazi', 'NAZI',
        'pela', 'Pela', 'PELA',
        'pelas', 'Pelas', 'PELAS',
        'mierda', 'Mierda', 'MIERDA',
        'caca', 'Caca', 'CACA',
        'kaka', 'Kaka', 'KAKA',
        'popo', 'Popo', 'POPO',
        'pendejos', 'Pendejos', 'PENDEJOS',
        'putos', 'Putos', 'PUTOS',
        'putas', 'Putas', 'PUTAS',
        'ramera', 'Ramera', 'RAMERA',
        'perro', 'Perro', 'PERRO',
        'perra', 'Perra', 'PERRA',
        'perros', 'Perros', 'PERROS',
        'perras', 'Perras', 'PERRAS',
        'pela', 'Pela', 'PELA',
        'pelan', 'Pelan', 'PELAN',
        'pelas', 'Pelas', 'PELAS',
        'chinga', 'Chinga', 'CHINGA',
        'chingue', 'Chingue', 'CHINGUE',
        'chinguen', 'Chinguen', 'CHINGUEN',
        'mames', 'Mames', 'MAMES',
        'nomames', 'NoMames', 'NOMAMES',
        'estupido', 'Estupido', 'ESTUPIDO',
        'estupida', 'Estupida', 'ESTUPIDA',
        // Palabras adicionales
        'imbecil', 'Imbecil', 'IMBECIL',
        'idiota', 'Idiota', 'IDIOTA',
        'tarado', 'Tarado', 'TARADO',
        'tarada', 'Tarada', 'TARADA',
        'bastardo', 'Bastardo', 'BASTARDO',
        'bastarda', 'Bastarda', 'BASTARDA',
        'cabron', 'Cabron', 'CABRON',
        'cabrona', 'Cabrona', 'CABRONA',
        'hijo de puta', 'Hijo de puta', 'HIJO DE PUTA',
        'hija de puta', 'Hija de puta', 'HIJA DE PUTA',
        'mierdero', 'Mierdero', 'MIERDERO',
        'mierdera', 'Mierdera', 'MIERDERA',
        'culo', 'Culo', 'CULO',
        'puto', 'Puto', 'PUTO',
        'zorra', 'Zorra', 'ZORRA',
    ],
];
